on:
  pull_request:
  push:
    branches:
      - master
name: CI
jobs:
  packages:
    name: Package sanity tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Hermit
        run: |
          set -e
          set -o pipefail
          curl -fsSL https://github.com/cashapp/hermit/releases/download/stable/install.sh | bash
      - name: Test packages
        run: |
          set -xe -o pipefail
          ~/bin/hermit validate "file://$PWD"
          .github/scripts/test-changed.sh
